apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zar-brez-utvar
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: zar-brez-utvar
    newName: rg.fr-par.scw.cloud/djnd/zar-brez-utvar
    newTag: 'ac0399ff6c9aae40bc509760c909d0fedfa920d7'
