apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zar-brez-utvar
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: zar-brez-utvar
    newName: rg.fr-par.scw.cloud/djnd/zar-brez-utvar
    newTag: '6d1fc101b5f2ffb53f71b54cfa34ea95a6022244'
